;; (use-package speed-type)
;; (use-package parrot
  ;; :config
  ;; (parrot-mode))

;; (use-package doom-modeline
;;   :ensure t
;;   :hook (after-init . doom-modeline-mode))

;; (custom-set-faces
;;   ;; '(mode-line ((t (:background "#302A29" :foreground "#e5d5b8"))))
;;   '(doom-modeline-bar ((t (:background "#302A29" :inherit mode-line)))))

;; (setq doom-modeline-support-imenu t)
;; (setq doom-modeline-height 25)
;; (setq doom-modeline-height 2)
;; (setq doom-modeline-bar-width 2)
;; (setq doom-modeline-hud nil)
;; (setq doom-modeline-window-width-limit 85)
;; (setq doom-modeline-project-detection 'auto)
;; (setq doom-modeline-buffer-file-name-style 'auto)
;; (setq doom-modeline-icon t)
;; (setq doom-modeline-major-mode-icon t)
;; (setq doom-modeline-major-mode-color-icon t)
;; (setq doom-modeline-buffer-state-icon t)
;; (setq doom-modeline-buffer-modification-icon t)
;; (setq doom-modeline-time-icon t)
;; (setq doom-modeline-unicode-fallback nil)
;; (setq doom-modeline-buffer-name t)
;; (setq doom-modeline-minor-modes nil)
;; (setq doom-modeline-enable-word-count nil)
;; (setq doom-modeline-continuous-word-count-modes '(markdown-mode gfm-mode org-mode))
;; (setq doom-modeline-buffer-encoding t)
;; (setq doom-modeline-indent-info nil)
;; (setq doom-modeline-checker-simple-format t)
;; (setq doom-modeline-number-limit 99)
;; (setq doom-modeline-vcs-max-length 12)
;; (setq doom-modeline-workspace-name t)
;; (setq doom-modeline-persp-name t)
;; (setq doom-modeline-display-default-persp-name nil)
;; (setq doom-modeline-persp-icon t)
;; (setq doom-modeline-lsp t)
;; (setq doom-modeline-github nil)
;; (setq doom-modeline-github-interval (* 30 60))
;; (setq doom-modeline-modal-icon t)
;; ;; (setq doom-modeline-mu4e nil)
;; ;; (mu4e-alert-enable-mode-line-display)
;; (setq doom-modeline-gnus t)
;; (setq doom-modeline-gnus-timer 2)
;; (setq doom-modeline-gnus-excluded-groups '("dummy.group"))
;; (setq doom-modeline-irc t)
;; (setq doom-modeline-irc-stylize 'identity)
;; (setq doom-modeline-time t)
;; (setq doom-modeline-display-misc-in-all-mode-lines t)
;; (setq doom-modeline-env-version t)
;; (setq doom-modeline-env-enable-python t)
;; (setq doom-modeline-env-enable-ruby t)
;; (setq doom-modeline-env-enable-perl t)
;; (setq doom-modeline-env-enable-go t)
;; (setq doom-modeline-env-enable-elixir t)
;; (setq doom-modeline-env-enable-rust t)
;; (setq doom-modeline-env-python-executable "python")
;; (setq doom-modeline-env-ruby-executable "ruby")
;; (setq doom-modeline-env-perl-executable "perl")
;; (setq doom-modeline-env-go-executable "go")
;; (setq doom-modeline-env-elixir-executable "iex")
;; (setq doom-modeline-env-rust-executable "rustc")
;; (setq doom-modeline-env-load-string "...")
;; (setq doom-modeline-before-update-env-hook nil)
;; (setq doom-modeline-after-update-env-hook nil)

;; (use-package gnugo)		;
;; (vuiet-tag-info "progressive rock")
;; (vuiet-album-info "steven wilson" "to the bone")
;; (vuiet-artist-info "steven wilson")

;; (use-package skype)
;; (setq skype--my-user-handle "rp813149@protonmail.com")
;; (use-package angular-snippets)
;; (use-package ac-html-angular)
