(defun generate-random-words (n)
  "Generate n non-repeated random words from a list of words and write them into the buffer where the cursor is located."
  (interactive "nNumber of words to generate: ")
  (let* ((words '("apple" "banana" "cherry" "date" "elderberry" "fig" "grape" "honeydew" "orange" "pear" "quince" "raspberry" "strawberry" "tangerine" "watermelon"))
         (num-words (length words))
         (random-words (make-hash-table :test 'equal))
         (buffer (current-buffer)))
    (dotimes (i n)
      (let ((random-word (nth (random num-words) words)))
        (while (gethash random-word random-words)
          (setq random-word (nth (random num-words) words)))
        (puthash random-word t random-words)
        (insert random-word)
        (when (< i (- n 1))
          (insert " "))))
    (insert "\n")))
